### ISSUE TITLE
GUARDAR NUEVO CAMPO EN BASE DE DATOS Y MOSTRARLO EN REPORTE DE COTIZACION Y FACTURA/COTIZACION

### ISSUE THREAD

**Issue by kenny1504** [kenny1504/LDCI#31]
GUARDAR NUEVO CAMPO SEGUN REQUERIMIENTO DEL CLIENTE Y MOSTRARLO EN REPORTE COTIZACION Y FACTURA/COTIZACION

-> Campo nota_adicional

**Comment by jsan98** [comment]
terminada
